# Generated by Django 2.2.6 on 2020-02-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Buy',
            field=models.IntegerField(),
        ),
    ]
