# Generated by Django 2.2.6 on 2020-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_buy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
