# Generated by Django 2.2.6 on 2020-02-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_buy_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cash', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
        ),
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name=0),
        ),
    ]
