# Generated by Django 2.2.6 on 2020-02-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200220_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='cash',
        ),
        migrations.AlterField(
            model_name='assets',
            name='btc',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=4, default=9526.54, max_digits=14),
        ),
    ]
