# Generated by Django 2.2.6 on 2020-02-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200220_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='cash',
            field=models.DecimalField(decimal_places=4, default=10000, max_digits=24),
        ),
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=4, default=9554.3183, max_digits=14),
        ),
    ]
