# Generated by Django 2.2.6 on 2020-02-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200220_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.AddField(
            model_name='buy',
            name='btc',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='buy',
            name='cash',
            field=models.DecimalField(decimal_places=4, default=10000.0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=4, default=9572.2933, max_digits=14),
        ),
    ]
