# Generated by Django 2.2.6 on 2020-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200220_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=4, default=8829.345, max_digits=14),
        ),
    ]
