# Generated by Django 2.2.6 on 2020-03-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200302_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=4, default=8842.02, max_digits=14),
        ),
    ]
